from flask.ext.wtf import Form
from wtforms import StringField, SelectField,SubmitField, validators
from wtforms import ValidationError

class SearchForm(Form):
    user_input = StringField(validators.DataRequired("Please enter a search entry."))
    agency_input = SelectField(choices=[
        (1, "All Agencies"),
        (2, "Aging"),
        (3, "Buildings"),
        (4, "Campaign Finance"),
        (5, "Children\'s Services"),
        (6, "City Council"),
        (7, "City Clerk"),
        (8, "City Planning"),
        (9, "Citywide Admin Svcs"),
        (10, "Civilian Complaint"),
        (11, "Comm - Police Corr"),
        (12, "Community Assistance"),
        (13, "Comptroller"),
        (14, "Conflicts of Interest"),
        (15, "Consumer Affairs"),
        (16, "Contracts"),
        (17, "Correction"),
        (18, "Criminal Justice Coordinator"),
        (19, "Cultural Affairs"),
        (20, "DOI - Investigation"),
        (21, "Design/Construction"),
        (22, "Disabilities"),
        (23, "District Atty, NY County"),
        (24, "Districting Commission"),
        (25, "Domestic Violence"),
        (26, "Economic Development"),
        (27, "Education, Dept. of"),
        (28, "Elections, Board of"),
        (29, "Emergency Mgmt."),
        (30, "Employment"),
        (31, "Empowerment Zone"),
        (32, "Environmental - DEP"),
        (33, "Environmental - OEC"),
        (34, "Environmental - ECB"),
        (35, "Equal Employment"),
        (36, "Film/Theatre"),
        (37, "Finance"),
        (38, "Fire"),
        (39, "FISA"),
        (40, "Health and Mental Hyg."),
        (41, "HealthStat"),
        (42, "Homeless Services"),
        (43, "Hospitals - HHC"),
        (44, "Housing - HPD"),
        (45, "Human Rights"),
        (46, "Human Rsrcs - HRA"),
        (47, "Immigrant Affairs"),
        (48, "Independent Budget"),
        (49, "Info. Tech. and Telecom."),
        (50, "Intergovernmental"),
        (51, "International Affairs"),
        (52, "Judiciary Committee"),
        (53, "Juvenile Justice"),
        (54, "Labor Relations"),
        (55, "Landmarks"),
        (56, "Law Department"),
        (57, "Library - Brooklyn"),
        (58, "Library - New York"),
        (59, "Library - Queens"),
        (60, "Loft Board"),
        (61, "Management and Budget"),
        (62, "Mayor"),
        (63, "Metropolitan Transportation Authority"),
        (64, "NYCERS"),
        (65, "Operations"),
        (66, "Parks and Recreation"),
        (67, "Payroll Administration"),
        (68, "Police"),
        (69, "Police Pension Fund"),
        (70, "Probation"),
        (71, "Public Advocate"),
        (72, "Public Health"),
        (73, "Public Housing-NYCHA"),
        (74, "Records"),
        (75, "Rent Guidelines"),
        (76, "Sanitation"),
        (77, "School Construction"),
        (78, "Small Business Svcs"),
        (79, "Sports Commission"),
        (80, "Standards and Appeal"),
        (81, "Tax Appeals Tribunal"),
        (82, "Tax Commission"),
        (83, "Taxi and Limousine"),
        (84, "Transportation"),
        (85, "Trials and Hearings"),
        (86, "Veterans - Military"),
        (87, "Volunteer Center"),
        (88, "Voter Assistance"),
        (89, "Youth & Community")], default=1)
    cat_input = SelectField(choices=[
        (1, "All Categories"),
        (2, "Business and Consumers"),
        (3, "Cultural/Entertainment"),
        (4, "Education"),
        (5, "Environment"),
        (6, "Finance and Budget"),
        (7, "Government Policy"),
        (8, "Health"),
        (9, "Housing and Buildings"),
        (10, "Human Services"),
        (11, "Labor Relations"),
        (12, "Public Safety"),
        (13, "Recreation/Parks"),
        (14, "Sanitation"),
        (15, "Technology"),
        (16, "Transportation")], default=1)
    type_input = SelectField(choices=[
        (1, "All Types"),
        (2, "Annual Report"),
        (3, "Audit Report"),
        (4, "Bond Offering - Official Statements"),
        (5, "Budget Report"),
        (6, "Consultant Report"),
        (7, "Guide - Manual"),
        (8, "Hearing - Minutes"),
        (9, "Legislative Document"),
        (10, "Memoranda - Directive"),
        (11, "Press Release"),
        (12, "Serial Publication"),
        (13, "Staff Report"),
        (14, "Report")], default=1)

    search = SubmitField()
